### ISSUE TITLE
Does the plugin verify the token?

### ISSUE THREAD

**Issue by basharov** [ryanfitz/hapi-auth-jwt#41]
I am trying the plugin out and want to make sure `expiresIn` options works.
When I create a token:

```javascript
var token = jwt.sign({accountId: 123}, privateKey, {expiresIn: '0'});
```

or

```javascript
var token = jwt.sign({accountId: 123}, privateKey, {expiresIn: '-1'});
```

Then just run the code from the example, it doesn't show it as a wrong token, sends all the restricted data.

Am I doing something wrong?

**Comment by edwardcodes** [comment]
Good question @basharov,
Yes, the plugin Verifies the JWT is valid.

I ***highly recommend*** using [***hapi-auth-jwt2***](https://github.com/dwyl/hapi-auth-jwt2) instead of **hapi-auth-jwt** because this module is *not* tested with the latest version of Hapi... [![peerDependency Status](https://david-dm.org/ryanfitz/hapi-auth-jwt/peer-status.svg)](https://david-dm.org/ryanfitz/hapi-auth-jwt#info=peerDependencies) 

See:
+ Verify in the plugin code:
https://github.com/dwyl/hapi-auth-jwt2/blob/master/lib/index.js#L58
+ Verify *Options*:
https://github.com/dwyl/hapi-auth-jwt2#verifyoptions-let-you-define-how-to-verify-the-tokens-optional
